services:
  server:
    build: ./server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 5000:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  dev:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client/src:/app/src
